# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      goals: ' mvn clean install'  # Include 'clean' to ensure a clean build
      codeCoverageToolOption: 'None'  # If you don't need code coverage reports

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/target'
      artifactName: 'test-results'

  - script: |
      # Download and install any required dependencies
      mvn verify
      # Adjust the command based on your specific requirements
    displayName: 'Install Maven Dependencies and run test'

  - script: |
      # Debugging: List the contents of the surefire-reports directory
      ls -R $(Build.SourcesDirectory)/target/surefire-reports
    displayName: 'List the contents of the surefire-reports directory'

#  - script: |
#      # Run your TestNG test suites
#      -Dtestng.config.path=$(Build.SourcesDirectory)/testng.xml
#      # Adjust the command based on your build tool and test suite configuration
#    displayName: 'Run TestNG tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'  # Specify the format of your test results
      testResultsFiles: '$(Build.SourcesDirectory)/target/surefire-reports/index.html'  # Update this path to match your XML files




