trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '15'
      jdkArchitectureOption: 'x64'

  - script: mvn -B package
    displayName: 'Build project with Maven'
