trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadSecureFile@1
    displayName: 'Download JDK 15'
    inputs:
      connection: '<YourServiceConnectionName>'
      path: '<PathToYourJDKBinary>'
      secureFile: 'jdk-15.tar.gz'

  - task: JavaToolInstaller@0
    displayName: 'Install JDK 15'
    inputs:
      versionSpec: '15'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'jdkFile'
      jdkFile: '$(Agent.TempDirectory)/jdk-15.tar.gz'

  - script: mvn -B package
    displayName: 'Build project with Maven'