trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadFile@1
    displayName: 'Download JDK 15'
    inputs:
      FileUrl: 'https://api.adoptopenjdk.net/v3/binary/latest/15/ga/linux/x64/jdk/hotspot/normal/adoptopenjdk?file_type=.tar.gz'
      DestinationFolder: '$(Build.BinariesDirectory)'
      ResultFileName: 'jdk-15.tar.gz'

  - task: JavaToolInstaller@0
    displayName: 'Install JDK 15'
    inputs:
      versionSpec: '15'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'jdkFile'
      jdkFile: '$(Build.BinariesDirectory)/jdk-15.tar.gz'

  - script: mvn -B package
    displayName: 'Build project with Maven'
