pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands: maven

steps:
  - script: |
      echo "Listing contents of src/main/resources/"
      ls -l src/main/resources/
    displayName: 'List contents of resources directory'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/src/main/resources'
      Contents: 'Test_Data.xls'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/resources'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/resources'
      ArtifactName: 'resources'

  - task: Maven@3
    displayName: 'Maven pom.xml'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test compile'
      testResultsFiles: '**/target/surefire-reports/junitreports/*.xml'
      testRunTitle: 'Test Run sample'
      allowBrokenSymlinks: false
      jdkVersionOption: 1.17

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.Artifactstagingdirectory)/target'
    inputs:
      SourceFolder: src
      Contents: '**/*.jar'
      TargetFolder: '$(build.DefaultWorkingDirectory)/target'
      CleanTargetFolder: true
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      pathToPublish: 'target'
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: '**/TEST-*.xml'
      failTaskOnFailedTests: true
      mergeTestResults: false
      testRunTitle: 'Regression Test'
    condition: succeededOrFailed()

  - task: CopyFiles@2
    displayName: 'Copy Screenshots to: $(Build.ArtifactStagingDirectory)/screenShots'
    inputs:
      SourceFolder: screenShots
      Contents: '*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/screenShots'
      CleanTargetFolder: true
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/screenShots'
      ArtifactName: 'drop'
      PublishLocation: 'Container'
      TargetPath: 'screenShotImages'
    condition: always()

