trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: '$(Build.SourcesDirectory)/src/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      goals: 'clean install'  # Build the project and install dependencies
      codeCoverageToolOption: 'None'

  - script: |
      # Run TestNG tests using a script
      test -Dsurefire.suiteXmlFiles=$(Build.SourcesDirectory)/src/main/resources/testng.xml
    displayName: 'Run TestNG Tests'

  - script: |
      # Debugging: List the contents of the surefire-reports directory
      ls -R $(Build.SourcesDirectory)
    displayName: 'List the contents of the surefire-reports directory'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/src/target/surefire-reports/junitreports/*.xml'
      testResultsFormat: 'JUnit'
      condition: always()
    displayName: 'Publish TestNG Test Results'