# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'src/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test -Dtestng.config.path=src/testng.xml'  # Include 'clean' to ensure a clean build
      codeCoverageToolOption: 'None'  # If you don't need code coverage reports

  - script: |
      mvn test -Dtestng.config.path=src/testng.xml
    displayName: 'Run TestNG tests'

